### ISSUE TITLE
readme 中的介绍文章链接失效

### ISSUE THREAD

**Issue by KingAmo** [flexih/SnakeList#1]
https://www.jianshu.com/p/c83d0ab1c3b2

**Comment by KingAmo** [comment]
另：有计划更新这个表格吗 :)

**Comment by flexih** [comment]
使用新链接替换了，https://www.floattower.com/blog/stack/

**Comment by flexih** [comment]
> 另：有计划更新这个表格吗 :)

可能今年会更新一波
